apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-webgoat-webwolf-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mygoat
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: mygoat
    spec:
      containers:
      - name: webgoat-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
