apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-webgoat-devsecops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mygoat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mygoat
    spec:
      containers:
      - name: webgoat-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
